const RU = {
  "header.eyebrow": "Рабочее пространство",
  "header.greeting": "Добро пожаловать, {name}",
  "header.subtitle": "{days} дней в команде · ваша доля {percent}%",
  "header.refresh": "Обновить",
  "header.period": "Период",
  "header.days": "дней",
  "demo.title": "Демонстрационные данные",
  "demo.text": "API не используется. Значения и события созданы только для предпросмотра интерфейса.",
  "stats.title": "Статистика за период",
  "stats.hint": "Ключевые результаты и изменение к прошлому периоду",
  "stats.profitTotal": "Общий профит",
  "stats.profitPeriod": "Профит за период",
  "stats.logs": "Логи",
  "stats.mafile": "MaFile",
  "stats.logsHint": "за период / всего",
  "stats.mafileHint": "за период / всего",
  "stats.deltaSuffix": " к прошлому периоду",
  "hero.label": "Общий результат",
  "hero.caption": "Доход за всё время",
  "hero.today": "Сегодня",
  "hero.period": "За {days} дней",
  "hero.share": "Ваша доля",
  "metric.logs": "Лог",
  "metric.logsHint": "{period} за период · {today} сегодня",
  "metric.mafiles": "MaFile",
  "metric.mafilesHint": "{period} за период · {today} сегодня",
  "metric.operations": "Операции",
  "metric.operationsHint": "За всё время",
  "metric.best": "Лучший результат",
  "metric.bestHint": "Максимальная выплата",
  "chart.title": "Динамика по периоду",
  "chart.subtitle": "Профит и активность по дням",
  "chart.profit": "Профит",
  "chart.logs": "Логи",
  "chart.mafiles": "MaFile",
  "chart.empty": "За выбранный период данных пока нет",
  "activity.title": "Список логов",
  "activity.subtitle": "{count} логов с текущими фильтрами",
  "activity.search": "Поиск по домену, ID или тегу",
  "activity.typeAll": "Все типы",
  "activity.logs": "Лог",
  "activity.mafiles": "MaFile",
  "activity.statusAll": "Все статусы",
  "activity.valid": "Лог",
  "activity.invalid": "Невалид",
  "activity.other": "Другой",
  "activity.sold": "Продан",
  "activity.onSale": "Продается",
  "activity.processed": "Отработан",
  "activity.sortNewest": "Сначала новые",
  "activity.sortOldest": "Сначала старые",
  "activity.sortExpensive": "Сначала дороже",
  "activity.sortCheapest": "Сначала дешевле",
  "activity.open": "Открыть детали",
  "activity.copyId": "Скопировать ID",
  "activity.copied": "ID скопирован",
  "activity.tipBalance": "Баланс",
  "activity.tipInventory": "Инвентарь",
  "activity.tipTradable": "Трейдятся",
  "activity.tipSteamId": "SteamID",
  "activity.tipLevel": "Уровень",
  "activity.tipGames": "Игры",
  "activity.tipGuard": "Guard",
  "activity.noResults": "По заданным условиям ничего не найдено",
  "activity.empty": "События появятся после первых операций",
  "activity.pagination": "Страницы списка логов",
  "activity.pagePrev": "Назад",
  "activity.pageNext": "Далее",
  "activity.pageInfo": "Страница {page} из {total}",
  "status.valid": "Лог",
  "status.invalid": "Невалид",
  "status.mafile": "MaFile",
  "status.other": "Без статуса",
  "status.empty": "Пустой",
  "status.hold": "На холде",
  "status.locked": "Заблокирован",
  "status.processing": "Обрабатывается",
  "status.sessionInvalidTitle": "Сессия невалидна",
  "status.sessionInvalid": "Предварительно сессия MaFile аккаунта невалидна",
  "status.sessionInvalidChecked": "Проверено {date}",
  "state.loading": "Собираем актуальную сводку",
  "state.loadingHint": "Обычно это занимает несколько секунд",
  "state.error": "Сводку не удалось загрузить",
  "state.retry": "Повторить",
  "state.demo": "Открыть демо",
  "state.partial": "Часть событий временно недоступна",
  "drawer.event": "Событие #{id}",
  "drawer.account": "Аккаунт",
  "drawer.adminNote": "Заметка админа",
  "drawer.total": "Общая стоимость",
  "drawer.balance": "Баланс",
  "drawer.inventory": "Инвентарь",
  "drawer.details": "Параметры аккаунта",
  "drawer.type": "Тип",
  "drawer.level": "Уровень",
  "drawer.levelValue": "{level} уровень",
  "drawer.country": "Страна",
  "drawer.lastPlayed": "Последний вход",
  "drawer.games": "Игры",
  "drawer.gamesPrev": "Предыдущие игры",
  "drawer.gamesNext": "Следующие игры",
  "drawer.tradable": "Доступно для обмена",
  "drawer.marketable": "Доступно на маркете",
  "drawer.inventorySummary": "{count} предметов · {total}",
  "drawer.noItems": "В этой игре нет предметов",
  "drawer.close": "Закрыть",
  "drawer.refresh": "Обновить данные",
  "drawer.check": "Проверить валид",
  "drawer.steam": "Открыть профиль",
  "drawer.sell": "Продать аккаунт",
  "drawer.process": "Отправить на отработку",
  "drawer.confirm": "Подтвердить действие",
  "drawer.cancel": "Отмена",
  "drawer.actionHint": "Действие изменит статус события. Нажмите подтверждение ещё раз.",
  "drawer.actionDone": "Запрос успешно отправлен",
  "drawer.updated": "Данные события обновлены",
  "drawer.checkSent": "Проверка запущена",
  "drawer.checkWaitTitle": "Проверяем валид",
  "drawer.checkWait": "Проверяем вход. Обычно это занимает до пары минут.",
  "drawer.checkValid": "Аккаунт валид",
  "drawer.checkValidBody": "Сессия подтверждена.",
  "drawer.checkInvalid": "Сессия невалидна",
  "drawer.checkInvalidBody": "Предварительно сессия MaFile аккаунта невалидна",
  "drawer.checkFailed": "Сессия невалидна",
  "drawer.checkTimeout": "Проверка ещё идёт",
  "drawer.checkTimeoutBody": "Результат появится чуть позже. Можно обновить карточку.",
  "drawer.loadError": "Детали недоступны. Показаны данные из ленты.",
} as const;

const EN: Record<keyof typeof RU, string> = {
  "header.eyebrow": "Workspace",
  "header.greeting": "Welcome back, {name}",
  "header.subtitle": "{days} days with the team · your share is {percent}%",
  "header.refresh": "Refresh",
  "header.period": "Period",
  "header.days": "days",
  "demo.title": "Demo data",
  "demo.text": "The API is not being used. Values and events are provided for interface preview only.",
  "stats.title": "Period statistics",
  "stats.hint": "Key results and change from the previous period",
  "stats.profitTotal": "Total profit",
  "stats.profitPeriod": "Period profit",
  "stats.logs": "Logs",
  "stats.mafile": "MaFile",
  "stats.logsHint": "period / total",
  "stats.mafileHint": "period / total",
  "stats.deltaSuffix": " vs previous period",
  "hero.label": "Overall result",
  "hero.caption": "All-time earnings",
  "hero.today": "Today",
  "hero.period": "{days} day result",
  "hero.share": "Your share",
  "metric.logs": "Log",
  "metric.logsHint": "{period} in period · {today} today",
  "metric.mafiles": "MaFile",
  "metric.mafilesHint": "{period} in period · {today} today",
  "metric.operations": "Operations",
  "metric.operationsHint": "All time",
  "metric.best": "Best result",
  "metric.bestHint": "Largest payout",
  "chart.title": "Period dynamics",
  "chart.subtitle": "Daily profit and activity",
  "chart.profit": "Profit",
  "chart.logs": "Logs",
  "chart.mafiles": "MaFile",
  "chart.empty": "There is no data for this period yet",
  "activity.title": "Log list",
  "activity.subtitle": "{count} logs with current filters",
  "activity.search": "Search by domain, ID or tag",
  "activity.typeAll": "All types",
  "activity.logs": "Log",
  "activity.mafiles": "MaFile",
  "activity.statusAll": "All statuses",
  "activity.valid": "Log",
  "activity.invalid": "Invalid",
  "activity.other": "Other",
  "activity.sold": "Sold",
  "activity.onSale": "On sale",
  "activity.processed": "Processed",
  "activity.sortNewest": "Newest first",
  "activity.sortOldest": "Oldest first",
  "activity.sortExpensive": "Highest value",
  "activity.sortCheapest": "Lowest value",
  "activity.open": "Open details",
  "activity.copyId": "Copy ID",
  "activity.copied": "ID copied",
  "activity.tipBalance": "Balance",
  "activity.tipInventory": "Inventory",
  "activity.tipTradable": "Tradable",
  "activity.tipSteamId": "SteamID",
  "activity.tipLevel": "Level",
  "activity.tipGames": "Games",
  "activity.tipGuard": "Guard",
  "activity.noResults": "No events match the selected filters",
  "activity.empty": "Events will appear after your first operations",
  "activity.pagination": "Log list pages",
  "activity.pagePrev": "Previous",
  "activity.pageNext": "Next",
  "activity.pageInfo": "Page {page} of {total}",
  "status.valid": "Log",
  "status.invalid": "Invalid",
  "status.mafile": "MaFile",
  "status.other": "No status",
  "status.empty": "Empty",
  "status.hold": "On hold",
  "status.locked": "Locked",
  "status.processing": "Processing",
  "status.sessionInvalidTitle": "Session is invalid",
  "status.sessionInvalid": "The MaFile account session looks invalid for now.",
  "status.sessionInvalidChecked": "Checked {date}",
  "state.loading": "Building your latest overview",
  "state.loadingHint": "This usually takes a few seconds",
  "state.error": "The overview could not be loaded",
  "state.retry": "Try again",
  "state.demo": "Open demo",
  "state.partial": "Some activity is temporarily unavailable",
  "drawer.event": "Event #{id}",
  "drawer.account": "Account",
  "drawer.adminNote": "Admin note",
  "drawer.total": "Total value",
  "drawer.balance": "Balance",
  "drawer.inventory": "Inventory",
  "drawer.details": "Account details",
  "drawer.type": "Type",
  "drawer.level": "Level",
  "drawer.levelValue": "level {level}",
  "drawer.country": "Country",
  "drawer.lastPlayed": "Last activity",
  "drawer.games": "Games",
  "drawer.gamesPrev": "Previous games",
  "drawer.gamesNext": "Next games",
  "drawer.tradable": "Tradable",
  "drawer.marketable": "Marketable",
  "drawer.inventorySummary": "{count} items · {total}",
  "drawer.noItems": "No items in this game",
  "drawer.close": "Close",
  "drawer.refresh": "Refresh data",
  "drawer.check": "Check validity",
  "drawer.steam": "Open profile",
  "drawer.sell": "Sell account",
  "drawer.process": "Send for processing",
  "drawer.confirm": "Confirm action",
  "drawer.cancel": "Cancel",
  "drawer.actionHint": "This action changes the event status. Confirm once more to continue.",
  "drawer.actionDone": "Request sent successfully",
  "drawer.updated": "Event data refreshed",
  "drawer.checkSent": "Validity check started",
  "drawer.checkWaitTitle": "Checking validity",
  "drawer.checkWait": "Checking the login. This can take a couple of minutes.",
  "drawer.checkValid": "Account is valid",
  "drawer.checkValidBody": "The session was confirmed.",
  "drawer.checkInvalid": "Session is invalid",
  "drawer.checkInvalidBody": "The MaFile account session looks invalid for now.",
  "drawer.checkFailed": "Session is invalid",
  "drawer.checkTimeout": "Check still running",
  "drawer.checkTimeoutBody": "The result will show up shortly. You can refresh the card.",
  "drawer.loadError": "Details are unavailable. Showing data from the activity stream.",
};

export type CopyKey = keyof typeof RU;

export function dashboardLanguage(): "ru" | "en" {
  const language =
    window.WorkerI18n?.lang?.() || window.WorkerPrefs?.get?.().lang || "ru";
  return String(language).toLowerCase().startsWith("en") ? "en" : "ru";
}

export function text(
  key: CopyKey,
  variables: Record<string, string | number> = {},
): string {
  let value = (dashboardLanguage() === "en" ? EN : RU)[key] || RU[key];
  for (const [name, replacement] of Object.entries(variables)) {
    value = value.replace(new RegExp(`\\{${name}\\}`, "g"), String(replacement));
  }
  return value;
}
